# Generated by Django 6.0.7 on 2026-07-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChaiVarify",
            new_name="ChaiVarity",
        ),
    ]
